### ISSUE TITLE
Error on Node 18

### ISSUE THREAD

**Issue by riovir** [indutny/node-ip#113] opened 2022-04-21 10:35 UTC
The `address()` function uses `os.networkInterfaces()`. A currently undocumented change in Node 18 resulted in the type of `defails.family` becoming a number.

Naturally, calling `.toLowerCase()` on the number throws an error.

**Comment by Apollon77** [comment] 2022-04-25 14:58
[see also https://github.com/indutny/node-ip/issues/113](https://github.com/nodejs/node/pull/41431#pullrequestreview-929717323)

**Comment by jaiswarvipin** [comment] 2022-04-27 19:20
Found issue in the "ip.js" code where family variable value coming in value. 

fix

On line 386 do following change

```
if(!isNaN(details.family)){
        details.family = ((details.family == 4)?"ipv4":"ipv6");
      }
      details.family = details.family.toLowerCase();
```

**Comment by Apollon77** [comment] 2022-04-27 19:39
@jaiswarvipin The fix is easy ... The problem is that this library is used in many others, so it would need new versions of this lib with the fix to be really useful

**Comment by jaiswarvipin** [comment] 2022-04-27 20:04
noted.

**Comment by jaiswarvipin** [comment] 2022-04-28 05:35
Proposed fix for IPV4 and IPv6 (Single m/c/ Scale set, Kubernetes, Mobile Device) working as expected. Kindly merge the code base in [main branch](https://github.com/jaiswarvipin/node-ip)

**Comment by sjoqvist** [comment] 2022-05-03 08:48
@megaandros You're correct that it's a workaround, but I'd argue that downgrading to Node 17 isn't a proper fix to "Error on Node 18".

It should also be noted that Node 17 goes end-of-life on June 1, i.e. in just 29 days.

**Comment by indutny** [comment] 2022-05-10 04:46
This should be fixed in the latest release. Sorry it took me so long to get to it.

**Closed by indutny** 2022-05-10 04:46 UTC

**Comment by Apollon77** [comment] 2022-05-10 06:33
Thank you very much(indeed ... the nodejs guys discuss reverting this breaking change btw ;-)))) ... but still anything ok with how you fixed it
